/**
 * Email shared by the cron scripts, modeled on the Discogs Notification On New Items one.
 */
import nodemailer from 'nodemailer'

/**
 * Locale used to format the dates and numbers of the emails. Read lazily: imports run before the env file is loaded.
 * @returns Locale.
 */
export function getLocale(): string {
    // `||`: an empty value would make every date formatting throw a RangeError.
    // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
    return process.env.LOCALE || 'en-US'
}

/** One entry listed in an email. */
export interface MailItem {
    /** Link opened by the entry. */
    readonly href: string
    /** Bold first line. */
    readonly title: string
    /** Plain lines under the title. */
    readonly lines: Array<string>
    /** Link shown in gray under the lines, when any. */
    readonly link?: string
    /** Thumbnail URL, when any. */
    readonly thumbnail?: string
}

/**
 * Escape text for HTML.
 * @param text - Text to escape.
 * @returns Escaped text.
 */
function escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/**
 * Format the current date and time for an email.
 * @returns Formatted date.
 */
function formatNow(): string {
    return new Date().toLocaleString(getLocale(), { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
}

/**
 * Build the HTML of an email.
 * @param intro - Sentence introducing the list, as HTML, completed with the current date.
 * @param items - Entries to list.
 * @returns HTML email.
 */
function buildMailHtml(intro: string, items: Array<MailItem>): string {
    const linkStyle = 'color: black; text-decoration: none'
    const thumbnailStyle = 'height: 100px; width: 100px; display: block; background: lightgray'
    const imageStyle = 'width: 100%; height: 100%; object-fit: contain; font-size: 0'
    const rows = items.map(item => {
        const href = escapeHtml(item.href)
        const thumbnail = item.thumbnail
            ? `
            <td>
                <a style="${thumbnailStyle}" href="${href}" target="_blank" rel="noopener">
                    <img style="${imageStyle}" src="${escapeHtml(item.thumbnail)}" alt="${escapeHtml(item.title)}" />
                </a>
            </td>`
            : ''
        const lines = item.lines.map(
            line => `
                <br />
                <a style="${linkStyle}" href="${href}" target="_blank" rel="noopener">${escapeHtml(line)}</a>`,
        )
        const link = item.link
            ? `
                <br />
                <a style="color: gray" href="${escapeHtml(item.link)}" target="_blank" rel="noopener">${escapeHtml(item.link)}</a>`
            : ''

        return `
        <tr>${thumbnail}
            <td${item.thumbnail ? ' style="padding-left: 10px"' : ''}>
                <a style="${linkStyle}" href="${href}" target="_blank" rel="noopener"><b>${escapeHtml(item.title)}</b></a>${lines.join('')}${link}
            </td>
        </tr>`
    })

    return `<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
    <div style="display: none; max-height: 0px; overflow: hidden">${items.map(item => escapeHtml(item.title)).join(' // ')}</div>
    <div style="display: none; max-height: 0px; overflow: hidden">${'&#847; &zwnj; &nbsp; &#8199; &shy;'.repeat(50)}</div>
    <p>${intro} at ${formatNow()}:</p>
    <table>${rows.join('')}
    </table>
    <br />
    <p style="font-size: 10px; font-style: italic">
        Automatically generated by
        <a href="https://github.com/KirianCaumes/In-Flames-Bootlegs" target="_blank" rel="noopener">In Flames Bootlegs</a>.
    </p>
</body>
</html>`
}

/**
 * Send an email listing entries, through the MAIL_* SMTP settings.
 * @param subject - Email subject.
 * @param intro - Sentence introducing the list, as HTML, completed with the current date.
 * @param items - Entries to list.
 */
export async function sendMail(subject: string, intro: string, items: Array<MailItem>): Promise<void> {
    await nodemailer
        .createTransport({
            host: process.env.MAIL_HOST,
            port: Number(process.env.MAIL_PORT),
            secure: process.env.MAIL_PORT === '465',
            auth: { user: process.env.MAIL_USER, pass: process.env.MAIL_PASS },
        })
        .sendMail({
            from: { address: process.env.MAIL_FROM ?? '', name: 'In Flames Bootlegs Bot' },
            to: process.env.MAIL_TO,
            subject,
            html: buildMailHtml(intro, items),
        })
}

/**
 * Link to the archive Google Sheet.
 * @returns Sheet URL.
 */
export function getSheetLink(): string {
    return `https://docs.google.com/spreadsheets/d/${process.env.GOOGLE_SHEET_ID ?? ''}/edit`
}
