/**
 * Dead link checker, meant to be run by a cron: `npm run check-links` (`-- --dry-run` to only print).
 *
 * Checks the `Link` of every row, emails the dead ones, then prefixes their title with 💀 in the sheet.
 * 💀 rows are skipped, so a dead link is reported once. Removing the 💀 once it is restored puts it back under watch.
 */
import nextEnv from '@next/env'
import nodemailer from 'nodemailer'
import { getGoogleAccessToken } from '../src/lib/google/auth.ts'
import type { GoogleApiResponse } from '../src/lib/google/sheets.ts'

nextEnv.loadEnvConfig(process.cwd())

/** Sheet tabs to check. */
const SHEETS = ['Live show', 'Various']

/** Prefix marking a sheet row as deleted. Mirrors `DELETED_TITLE_PREFIX`, which cannot be imported without the `lib/*` path alias. */
const DELETED_TITLE_PREFIX = '💀'

/** Locale used to format the date and numbers of the email. */
const LOCALE = process.env.LOCALE ?? 'en-US'

/** A sheet row whose link is dead. */
interface DeadRow {
    /** Title cell, in A1 notation. */
    readonly cell: string
    /** Sheet tab. */
    readonly sheet: string
    /** 1-based sheet row. */
    readonly row: number
    /** Row title. */
    readonly title: string
    /** Row date, as written in the sheet. */
    readonly date: string
    /** Dead link. */
    readonly link: string
}

/**
 * Escape text for HTML.
 * @param text - Text to escape.
 * @returns Escaped text.
 */
function escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/**
 * Build the report email, modeled on the Discogs Notification On New Items one.
 * @param rows - Dead rows to list.
 * @returns HTML email.
 */
function buildMailHtml(rows: Array<DeadRow>): string {
    const sheetLink = `https://docs.google.com/spreadsheets/d/${process.env.GOOGLE_SHEET_ID ?? ''}/edit`
    const date = new Date().toLocaleString(LOCALE, {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
    })
    const linkStyle = 'color: black; text-decoration: none'
    const items = rows.map(row => {
        const location = `${escapeHtml(row.sheet)}, row ${row.row}${row.date ? ` (${escapeHtml(row.date)})` : ''}`
        return `
        <tr>
            <td>
                <a style="${linkStyle}" href="${sheetLink}" target="_blank" rel="noopener"><b>${escapeHtml(row.title)}</b></a>
                <br />
                <a style="${linkStyle}" href="${sheetLink}" target="_blank" rel="noopener">${location}</a>
                <br />
                <a style="color: gray" href="${escapeHtml(row.link)}" target="_blank" rel="noopener">${escapeHtml(row.link)}</a>
            </td>
        </tr>`
    })

    return `<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Dead link(s)</title>
</head>
<body>
    <div style="display: none; max-height: 0px; overflow: hidden">${rows.map(row => escapeHtml(row.title)).join(' // ')}</div>
    <div style="display: none; max-height: 0px; overflow: hidden">${'&#847; &zwnj; &nbsp; &#8199; &shy;'.repeat(50)}</div>
    <p>
        <b>${rows.length.toLocaleString(LOCALE)}</b> dead link${rows.length > 1 ? 's' : ''} found in the
        <a href="${sheetLink}" target="_blank" rel="noopener">In Flames Bootlegs</a> sheet at ${date}, now marked with ${DELETED_TITLE_PREFIX}:
    </p>
    <table>${items.join('')}
    </table>
    <br />
    <p style="font-size: 10px; font-style: italic">
        Automatically generated by
        <a href="https://github.com/KirianCaumes/In-Flames-Bootlegs" target="_blank" rel="noopener">In Flames Bootlegs</a>.
    </p>
</body>
</html>`
}

/**
 * Tell whether a link is dead.
 * YouTube goes through the Data API: a watch page answers 200 even for a deleted video.
 * Anything else is dead on a 404 or 410 only, since 403 or 5xx are often bot protection or transient.
 * @param link - Link to check.
 * @returns True when the link is dead.
 */
async function isDead(link: string): Promise<boolean> {
    const url = new URL(link)

    if (url.hostname.endsWith('youtube.com') || url.hostname === 'youtu.be') {
        const videoId = url.hostname === 'youtu.be' ? url.pathname.slice(1) : url.searchParams.get('v')
        const [kind, id] = videoId ? ['videos', videoId] : ['playlists', url.searchParams.get('list')]
        const api = new URL(`https://www.googleapis.com/youtube/v3/${kind}`)
        api.searchParams.set('part', 'id')
        api.searchParams.set('id', id ?? '')
        api.searchParams.set('key', process.env.GOOGLE_API_KEY ?? '')
        const response = await fetch(api)
        if (!response.ok) {
            throw new Error(`YouTube API failed: HTTP ${response.status}`)
        }

        // Deleted and private resources are missing from the response.
        return (
            (
                (await response.json()) as {
                    /** Resources found: deleted and private ones are missing. */
                    readonly items: Array<unknown>
                }
            ).items.length === 0
        )
    }

    const response = await fetch(link, {
        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36' },
    })
    return response.status === 404 || response.status === 410
}

const token = await getGoogleAccessToken('https://www.googleapis.com/auth/spreadsheets')
const sheetUrl = `https://sheets.googleapis.com/v4/spreadsheets/${process.env.GOOGLE_SHEET_ID ?? ''}/values`
const deadRows: Array<DeadRow> = []

for (const sheet of SHEETS) {
    const response = await fetch(`${sheetUrl}/${encodeURIComponent(`${sheet}!A1:Z9999`)}`, {
        headers: { Authorization: `Bearer ${token}` },
    })
    const [headers = [], ...rows] = ((await response.json()) as GoogleApiResponse).values ?? []
    const titleColumn = headers.indexOf('Title')
    const linkColumn = headers.indexOf('Link')
    const dateColumn = headers.indexOf('Date')

    for (const [index, row] of rows.entries()) {
        const title = row[titleColumn] ?? ''
        const link = row[linkColumn]?.trim()
        if (title && link && !title.startsWith(DELETED_TITLE_PREFIX) && (await isDead(link))) {
            // + 2: rows are 1-based and the header row was taken out.
            deadRows.push({
                cell: `${sheet}!${String.fromCharCode(65 + titleColumn)}${index + 2}`,
                sheet,
                row: index + 2,
                title,
                date: row[dateColumn] ?? '',
                link,
            })
        }
    }
}

const report = deadRows.map(row => `- ${row.cell} ${row.title}: ${row.link}`).join('\n')
console.log(`${deadRows.length} dead link(s)\n${report}`)

if (deadRows.length > 0 && !process.argv.includes('--dry-run')) {
    // Mail first: if sending fails, the rows are not marked and get reported on the next run.
    await nodemailer
        .createTransport({
            host: process.env.MAIL_HOST,
            port: Number(process.env.MAIL_PORT),
            secure: process.env.MAIL_PORT === '465',
            auth: { user: process.env.MAIL_USER, pass: process.env.MAIL_PASS },
        })
        .sendMail({
            from: { address: process.env.MAIL_FROM ?? '', name: 'In Flames Bootlegs Bot' },
            to: process.env.MAIL_TO,
            subject: `In Flames Bootlegs - ${deadRows.length.toLocaleString(LOCALE)} dead link(s)`,
            html: buildMailHtml(deadRows),
        })

    const response = await fetch(`${sheetUrl}:batchUpdate`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
            valueInputOption: 'RAW',
            data: deadRows.map(row => ({ range: row.cell, values: [[`${DELETED_TITLE_PREFIX} ${row.title}`]] })),
        }),
    })
    if (!response.ok) {
        throw new Error(`Failed to mark dead rows: HTTP ${response.status} ${await response.text()}`)
    }
}
